version: '3.5'
services: 
  postgres:
    image: 'postgres:latest'
    restart: always
    networks:
      - workflow
    ports:
      - '5555:5432'

  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    networks:
      - workflow

  api:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules #do not try overwrite it
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
    networks:
      - workflow
    ports:
      - '8000:8000'

# Environment Variables
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    networks:
      - workflow

networks:
  workflow:
    # Use a custom driver
    name: workflow
    driver: bridge
    

