version: '3'
services: 
  postgres:
    image: 'postgres:latest'
    restart: always
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules #do not try overwrite it
      - ./server:/app
    environment:
      - PGUSER=perry
      - PGHOST=postgres
      - PGDATABASE=UserAuth
      - PGPASSWORD=Spf13609629560
      - PGPORT=5432
    

# Environment Variables
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
