version: '3'
services: 
  postgres:
    image: 'postgres:latest'
    restart: always
  api:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules #do not try overwrite it
      - ./:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports:
      - "8000:8000"