version: '3.5'
services: 
  api_test:
    build:
      dockerfile: Dockerfile.test.dev
      context: .
    volumes:
      - /app/node_modules #do not try overwrite it
      - ./:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
    networks:
      - workflow-test
networks:
  workflow-test:
    external: 
      name: workflow
